apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: web
        # Ditt Docker Hub repo er satt inn her:
        image: oddair/oddair:latest 
        ports:
        - containerPort: 8080
